import type { Metadata } from "next";
import { Cairo, Poppins } from "next/font/google";

import './globals.css'

const cairo = Cairo({
  subsets: ["latin", "latin-ext"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});
const lang: 'en' | 'ar' = "en";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

   // Replace with logic to detect language, e.g., from cookies, context, or user settings
  const fontClassName = lang === "en" ? cairo.className : poppins.className;

  return (

 <html lang={lang}>
      <body className={fontClassName}>
        {children}
      </body>
    </html>
   
  
  );
}
